### ISSUE TITLE
Tap reports have a "StringDescription object" in them

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#62] opened 2024-04-16 03:06 UTC
Example:

```
not ok 5 - webfinger.server.4_2__4_do_not_accept_malformed_resource_parameters2
  ---
  problem: |
    TestProblem(test=TestPlanTestSpec(name='webfinger.server.4_2__4_do_not_accept_malformed_resource_parameters2', disabled=None), exc=AssertionError(<hamcrest.core.string_description.StringDescription object at 0x103973e30>))
```

That `StringDescription` probably carries a better error message.

**Comment by steve-bate** [comment] 2024-04-17 09:13
After pulling changes and re-installing feditest in the UBOS container, when I run the fediverse-sandbox plan, I'm seeing:

![image](https://github.com/fediverse-devnet/feditest/assets/789524/3f0764fc-138c-4f26-8cfd-b8a47b4234a6)

Can you confirm this works for you?

**Comment by jernst** [comment] 2024-04-17 17:00
This is the intentionally faulty implementation, so we can see what happens if a test fails (note the name of the Driver: `SandboxMultServerDriver_Implementation3_Faulty`).

**Comment by steve-bate** [comment] 2024-04-17 17:44
> This is the intentionally faulty implementation, so we can see what happens if a test fails (note the name of the Driver: `SandboxMultServerDriver_Implementation3_Faulty`).

Yes, I used this test for that purpose (because it fails and reports a problem). I was able to reproduce the issue you described with this test before re-installing my container’s `feditest` application. After the re-install with the latest git commits, I see the correct problem formatting. That’s what I wanted to confirm.

**Comment by steve-bate** [comment] 2024-04-20 05:11
Sorry about the status flapping. I'm not sure what that option does (if it's issue-level or project-level). In any case, is it ok to close this issue?

**Closed** 2024-05-02 21:11 UTC
